Address: "127.0.0.1"
Port: 8024

LogDir: ./log
ResultDir: ./data
Storage: ./Storage
PostStorage: ./PostStorage

GitlabUrl: http://gpon.git.com:8011
Project_ID: 34

PrivateToken: 4mU2joxotSkzTqLPhvgu

TimeZone: +8:00

WaitingInterval: 10

BuildSet:
  Builds:
    GL5610:
        cmd:
        - sleep 10
        - echo ll <version> <datetime> > ll
        output:
        - ./ll

    GL5610-v2:
        cmd:
        - sleep 10
        - echo ll2 <version> <datetime> > ll2
        output:
        - ./ll2

    GL5610-v3:
        cmd:
        - sleep 10
        - echo ll3 <version> <datetime> > ll3
        output:
        - ./ll3

    GL8900:
        cmd:
        - sleep 10
        - echo ll4 <version> <datetime> > ll4
        output:
        - ./ll4

  Posts:
    P1:
      group:
        - GL5610
        - GL5610-v2
        - GL5610-v3
      cmd:
        - cat ll ll2 ll3 <version> <datetime> > post
      output:
        - ./post

    P2:
      group:
        - GL8900
      cmd:
        - cat ll4 <version> <datetime> > post_gl8900
        - echo 8900 <version> <datetime> >> post_gl8900
      output:
        - ./post_gl8900

  Merge:
    cmd:
      - cat * <version> <datetime> > <version>total
    output:
      - ./<version>total
