Address: "127.0.0.1"
Port: 30000

LogDir: ./log
ResultDir: ./data
Storage: ./Storage
PostStorage: ./PostStorage

GitlabUrl: http://10.5.4.211:8011
Project_ID: 34

PrivateToken: 4mU2joxotSkzTqLPhvgu

TimeZone: +8:00

WaitingInterval: 2

BuildSet:
  Builds:
    GL5610:
        cmd:
        - mv scancode-toolkit-3.1.1.zip scancode-toolkit-3.1.1_1.zip
        output:
        - ./scancode-toolkit-3.1.1_1.zip

    GL5610-v2:
        cmd:
        - mv scancode-toolkit-3.1.1.zip scancode-toolkit-3.1.1_2.zip
        output:
        - ./scancode-toolkit-3.1.1_2.zip

    GL5610-v3:
        cmd:
        - mv scancode-toolkit-3.1.1.zip scancode-toolkit-3.1.1_3.zip
        output:
        - ./scancode-toolkit-3.1.1_3.zip

    GL8900:
        cmd:
        - mv scancode-toolkit-3.1.1.zip scancode-toolkit-3.1.1_4.zip
        output:
        - ./scancode-toolkit-3.1.1_4.zip

  Merge:
    cmd:
      - cat scancode-toolkit-3.1.1_1.zip scancode-toolkit-3.1.1_2.zip scancode-toolkit-3.1.1_3.zip scancode-toolkit-3.1.1_4.zip > scancode-toolkit-3.1.1.zip
    output:
      - ./scancode-toolkit-3.1.1.zip

BuildSet_TWO:
  Builds:
    GL5610:
        cmd:
        - echo ll <version> <datetime> > ll
        output:
        - ./ll

    GL5610-v2:
        cmd:
        - echo ll2 <version> <datetime> > ll2
        output:
        - ./ll2
  Merge:
    cmd:
      - cat * > <version>total
    output:
      - ./<version>total
