BuildSet:
  Builds:
    GL5610:
        cmd:
        - ...
        - ...
        output:
        - ...

    GL5610-v2:
        cmd:
        - ...
        - ...
        output:
        - ...

    GL5610-v3:
        cmd:
        - ...
        - ...
        output:
        - ...

    GL8900:
        cmd:
        - ...
        - ...
        output:
        - ...

  Posts:
    GL5610_OEM:
      group:
        - GL5610
        - GL5610-v2
        - GL5610-v3
      cmd:
        - link_GL5610.bat
      output:
        - "C:\\pack.rar"

    GL8900_OEM:
      group:
        - GL8900
      cmd:
        - ...
      output:
        - "C:\\pack.rar"

  Merge:
    cmd:
      - ...
      - ...
    output:
      -...
