Address: "127.0.0.1"
Port: 8024

LogDir: ./log
ResultDir: ./data
Storage: ./Storage

GitlabUrl: http://gpon.git.com:8011
Project_ID: 34

PrivateToken: 4mU2joxotSkzTqLPhvgu

TimeZone: +8:00

WaitingInterval: 10

BuildSet:
  Builds:
    GL5610:
      cmd:
        - .\GBN\src\gcom_gpon_build_boot.bat 1
        - .\GBN\src\gcom_gpon_build_host.bat 1
        - cd .\BSP\config\image
        - rar a -r 5610gpon NOBRAND_OEM_TiNetS5610_10gpon
        - cd ..\..\..
      output:
        - .\BSP\config\image\5610gpon.rar

    GL5610-v3:
      cmd:
        - .\GBN\src\gcom_gpon_build_boot.bat 2
        - .\GBN\src\gcom_gpon_build_host.bat 2
        - cd .\BSP\config\image
        - rar a -r 5610gpon_v3 NOBRAND_OEM_TiNetS5610_10gpon_v3
        - cd ..\..\..
      output:
        - .\BSP\config\image\5610gpon_v3.rar

    GL8900_line:
      cmd:
        - .\GBN\src\gcom_gpon_build_boot.bat 6
        - .\GBN\src\gcom_gpon_build_host.bat 6
        - cd .\BSP\config\image
        - rar a -r 8900_line NOBRAND_OEM_gcom_gpon_8900_line
        - cd ..\..\..
      output:
        - .\BSP\config\image\8900_line.rar

    GL8900_ctrl:
      cmd:
        - .\GBN\src\gcom_gpon_build_boot.bat 5
        - .\GBN\src\gcom_gpon_build_host.bat 5
        - cd .\BSP\config\image
        - rar a -r 8900_ctrl NOBRAND_OEM_gcom_gpon_8900_ctrl
        - cd ..\..\..
      output:
        - .\BSP\config\image\8900_ctrl.rar

  Posts:
    GL5610_link:
      group:
        - GL5610
        - GL5610-v3
      cmd:
        - rar x 5610gpon.rar
        - rar x 5610gpon_v3.rar
        - link_hybrid_gl5610.bat
      output:
        - ./pack

    GL8900_link:
      group:
        - GL8900_line
        - GL8900_ctrl
        - link_image_gl89.bat
      cmd:
        - rar x 8900_line.rar
        - rar x 8900_ctrl.rar
      output:
        - ./pack

  Merge:
    cmd:
      - rar a -r <version> pack
    output:
      - ./<version>.rar
