BuildSet:
  Builds:
    GL5610:
        cmd:
        - touch ll
        output:
        - ./ll

    GL5610-v2:
        cmd:
        - touch ll2
        output:
        - ./ll2

    GL5610-v3:
        cmd:
        - touch ll3
        output:
        - ./ll3

    GL8900:
        cmd:
        - touch ll4
        output:
        - ./ll4

  Posts:
    GL5610_OEM:
      group:
        - GL5610
        - GL5610-v2
        - GL5610-v3
      cmd:
        - touch post
      output:
        - ./post

    GL8900_OEM:
      group:
        - GL8900
      cmd:
        - touch post_gl8900
      output:
        - ./post_gl8900

  Merge:
    cmd:
      - touch merge
    output:
      - ./merge
