Address: "127.0.0.1"
Port: 8024

LogDir: ./log
ResultDir: ./data
Storage: ./Storage

GitlabUrl: http://gpon.git.com:8011
Project_ID: 34

PrivateToken: 4mU2joxotSkzTqLPhvgu

TimeZone: +8:00

WaitingInterval: 10
