MASTER_ADDRESS:
  host: "127.0.0.1"
  port: 8024

WORKER_NAME: WORKER_EXAMPLE

REPO_URL: git@gpon.git.com:gpon/olt.git

PROJECT_NAME:  olt

QUEUE_SIZE: 1024

MAX_TASK_CAN_PROC: 4

PROCESS_POOL_SIZE: 4

RESULT_PATH: ./BSP/config/image/link/pack.rar

BUILDING_CMDS:
  - sleep 60
